# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: 
      - main
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Pull request have been merged in main
        run: |-
          latest_commit_message=$(git log -1 --pretty=%B)
          release_tag=$(echo "$latest_commit_message" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+")
          git tag "$release_tag"
          git push --tags
