name: CI

on:
  push:
    branches: [ "version/[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |-
          version="${GITHUB_REF#refs/heads/version/}"
          if [ $(git tag -l "$version") ]; then
            echo "Version $version already exists"
            exit 1
          exit
