name: CI

on:
  push:
    branches: [ "version/[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "We are on a branch preparing future version ${GITHUB_REF#refs/heads/version/}}"
