name: CI

on:
  pull_request:
    types:
      - opened
    branches:
      - "version/[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ensure git tag does not already exists
        run: |-
          version="${GITHUB_REF#refs/heads/version/}"
          if [ $(git tag -l "$version") ]; then
            echo "Version $version already exists"
            exit 1
          fi
