name: Create Release

on:
  pull_request:
    branches:
      - "main"
      #- "version/[0-9]+.[0-9]+.[0-9]+"
    types:
      - closed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }} && startsWith(github.event.pull_request.head.ref, 'version/')
    
    steps:
      - uses: actions/checkout@v3

      - name: Validate version
        id: validate_version
        run: |-
          src_branch="${{ github.event.pull_request.head.ref }}"
          version="${src_branch#version/}"
          echo "$src_branch $version"
          if [ $(git tag -l "$version") ]; then
            echo "Version $version already exists"
            exit 1
          fi
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create git tag
        run: |-
          git tag "${{ steps.validate_version.outputs.version }}"
          git push --tags
