name: Create Release

on:
  pull_request:
    branches:
      - "main"
      - "version/[0-9]+.[0-9]+.[0-9]+"
    types:
      - closed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}

    steps:
      - uses: actions/checkout@v3

      - name: Ensure git tag does not already exists
        run: |-
          version="${GITHUB_REF#refs/heads/version/}"
          if [ $(git tag -l "$version") ]; then
            echo "Version $version already exists"
            exit 1
          fi

      - name: Create git tag
        if: ${{steps.get_release_id.outputs.release_tag}}
        run: |-
          git tag "${GITHUB_REF#refs/heads/version/}"
          git push --tags
